---

- name: "Ensure {{ exim4_dkim_keys_path }} exists"
  action: file
  args:
    path: "{{ exim4_dkim_keys_path }}"
    state: directory
    owner: Debian-exim
    group: Debian-exim
    mode: 0700

- name: Generate DKIM private key
  command: openssl genrsa -out dkim.private {{ exim4_dkim_keysize }} -outform PEM
  args:
    chdir: "{{ exim4_dkim_keys_path }}"
    creates: "{{ exim4_dkim_keys_path }}/dkim.private"
  notify: reload exim4
  tags:
    - exim4
    - exim4-dkim

- name: Setup DKIM public key
  command: openssl rsa -in dkim.private -out dkim.public -pubout -outform PEM
  args:
    chdir: "{{ exim4_dkim_keys_path }}"
    creates: "{{ exim4_dkim_keys_path }}/dkim.public"
  notify: reload exim4
  tags:
    - exim4
    - exim4-dkim

- name: Setup private key permissions
  action: file
  args:
    dest: "{{ item.name }}"
    owner: root
    group: Debian-exim
    mode: "{{ item.mode }}"
  with_items:
    - name: "{{ exim4_dkim_keys_path }}/dkim.private"
      mode: 640
    - name: "{{ exim4_dkim_keys_path }}/dkim.public"
      mode: 644
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - exim4
    - exim4-dkim
